# Streamlit Secrets Configuration
# Gemini API Key
GEMINI_API_KEY = "AIzaSyDkZgeLXhKJrjclXXv27YDv0U_2o8meE6c"

# API Key is now configured and ready to use!
# The chatbot will be available in the dashboard 